columns:
  - age: Integer
  - workclass: varchar
  - fnlwgt: Integer
  - education-num: Integer
  - education: varchar
  - marital-status: varchar
  - occupation: varchar
  - relationship: varchar
  - race: varchar
  - sex: varchar
  - capital-gain: Integer
  - capital-loss: Integer
  - hours-per-week: Integer
  - native-country: varchar
  - Income: varchar

feature_columns:
  - age: Integer
  - workclass: varchar
  - fnlwgt: Integer
  - education-num: Integer
  - education: varchar
  - marital-status: varchar
  - occupation: varchar
  - relationship: varchar
  - race: varchar
  - sex: varchar
  - capital-gain: Integer
  - capital-loss: Integer
  - hours-per-week: Integer
  - native-country: varchar

drop_columns:
  - education

numerical_columns:
  - age
  - fnlwgt
  - education-num
  - capital-gain
  - capital-loss
  - hours-per-week

categorical_columns:
  - workclass
  - marital-status
  - occupation
  - relationship
  - race
  - sex
  - native-country

num_features:
  - age
  - fnlwgt
  - education-num
  - capital-gain
  - capital-loss
  - hours-per-week

or_columns:
  - workclass
  - marital-status
  - occupation
  - relationship
  - race
  - sex

oh_columns:
  - native-country

